## Preprocessing

In [1]:
# Import our dependencies

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf



#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 5.7 MB/s eta 0:00:00

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace
# optimization attempt 1, up cutoff value to 1,000
application_types_to_replace = list(app_type_count[app_type_count < 1000].index)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_greater_than_one = classification_counts.loc[classification_counts > 1]
classification_counts_greater_than_one.head()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_cat_conversion = pd.get_dummies(application_df)
application_cat_conversion.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_cat_conversion.drop(['IS_SUCCESSFUL'], axis=1)
y = application_cat_conversion['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_node_layer1 = 10
hidden_node_layer2 = 5

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units = hidden_node_layer1, input_dim = number_input_features,
                                   activation = "relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units = hidden_node_layer2, activation = "relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="tanh"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                410

 dense_1 (Dense)             (None, 5)                 55

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 471
Trainable params: 471
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 4.5845 - accuracy: 0.5234
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 1.2708 - accuracy: 0.6330
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.9643 - accuracy: 0.6713
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.8147 - accuracy: 0.6714
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7843 - accuracy: 0.6776
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.7504 - accuracy: 0.6976
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7157 - accuracy: 0.7042
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.7144 - accuracy: 0.6989
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6266 - accuracy: 0.7056
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6151 - accuracy: 0.7171
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6102 - accuracy: 0.7220
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6048 - accuracy: 0.7250
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6021 - accuracy: 0.7255
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6000 - accuracy: 0.7254
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5995 - accuracy: 0.7260
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5971 - accuracy: 0.7273
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5932 - accuracy: 0.7282
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5968 - accuracy: 0.7284
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5925 - accuracy: 0.7282
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5926 - accuracy: 0.7282
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5865 - accuracy: 0.7295
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5824 - accuracy: 0.7299
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5817 - accuracy: 0.7300
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5788 - accuracy: 0.7291
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5781 - accuracy: 0.7301
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5819 - accuracy: 0.7299
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5749 - accuracy: 0.7306
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5742 - accuracy: 0.7308
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5736 - accuracy: 0.7307
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5751 - accuracy: 0.7296
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5754 - accuracy: 0.7310
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5753 - accuracy: 0.7312
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5742 - accuracy: 0.7307
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5731 - accuracy: 0.7302
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5730 - accuracy: 0.7304
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5738 - accuracy: 0.7315
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5731 - accuracy: 0.7315
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5734 - accuracy: 0.7314
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5725 - accuracy: 0.7314
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5754 - accuracy: 0.7314
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5732 - accuracy: 0.7306
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5728 - accuracy: 0.7309
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5726 - accuracy: 0.7311
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5723 - accuracy: 0.7320
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5727 - accuracy: 0.7310
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5734 - accuracy: 0.7318
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5739 - accuracy: 0.7311
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5734 - accuracy: 0.7311
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5721 - accuracy: 0.7320
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5719 - accuracy: 0.7320
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7323
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5678 - accuracy: 0.7318
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5670 - accuracy: 0.7318
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5672 - accuracy: 0.7320
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5700 - accuracy: 0.7314
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5677 - accuracy: 0.7315
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7309
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5689 - accuracy: 0.7311
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7316
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5673 - accuracy: 0.7314
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5668 - accuracy: 0.7317
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7311
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5668 - accuracy: 0.7317
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5679 - accuracy: 0.7324
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5703 - accuracy: 0.7318
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5680 - accuracy: 0.7322
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5676 - accuracy: 0.7315
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5676 - accuracy: 0.7323
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7320
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5701 - accuracy: 0.7318
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5735 - accuracy: 0.7320
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7316
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5693 - accuracy: 0.7313
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5698 - accuracy: 0.7314
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7321
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5694 - accuracy: 0.7318
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7318
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5700 - accuracy: 0.7288
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7321
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5723 - accuracy: 0.7324
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7317
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7321
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7318
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5663 - accuracy: 0.7326
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5683 - accuracy: 0.7324
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5692 - accuracy: 0.7312
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7318
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7324
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5677 - accuracy: 0.7325
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7311
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5673 - accuracy: 0.7320
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5632 - accuracy: 0.7329
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5651 - accuracy: 0.7317
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7322
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5685 - accuracy: 0.7326
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5677 - accuracy: 0.7317
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5675 - accuracy: 0.7323
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5693 - accuracy: 0.7324
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5664 - accuracy: 0.7322
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5646 - accuracy: 0.7321

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5656 - accuracy: 0.7245 - 528ms/epoch - 2ms/step
Loss: 0.565625011920929, Accuracy: 0.7245481014251709

In [16]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization1.h5')